--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2019. 08. 29. 10:33:53
-- Server version: 5.5.5-10.4.6-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

CREATE DATABASE IF NOT EXISTS utak
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2019. 08. 29. 10:38:47
-- Server version: 5.5.5-10.4.6-MariaDB
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

--
-- Set default database
--
USE utak;

--
-- Create table `fizmodok`
--
CREATE TABLE IF NOT EXISTS fizmodok (
  id INT(11) NOT NULL,
  megnevezes VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS utadatok (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  taxiid INT(11) NOT NULL,
  indulasideje VARCHAR(50) DEFAULT NULL,
  idotartam INT(11) NOT NULL,
  tavolsag DECIMAL(5, 2) NOT NULL,
  viteldij DECIMAL(5, 2) DEFAULT NULL,
  borravalo DECIMAL(5, 2) DEFAULT NULL,
  fizmodid INT(11) NOT NULL,
  CONSTRAINT FK_utadatok_fizmodid FOREIGN KEY (fizmodid)
    REFERENCES fizmodok(id) ON DELETE NO ACTION
  
)
ENGINE = INNODB;

--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2019. 08. 29. 11:41:25
-- Server version: 5.5.5-10.4.6-MariaDB
-- Client version: 4.1
-- Please backup your database before running this script
--


